### ISSUE TITLE
Question about step size and input file

### ISSUE THREAD

**Issue by HLHsieh** [langjidong/NanoSTR#2]
Hi there,

Thank you for providing this exciting tool. I am new to this field, so I hope my question is not too naive. I am wondering how to set the "Step Size." Are there any suggestions or thinking tips for using it with my own data? Additionally, I would like to know whether this algorithm accepts a fasta file as an input.

Thank you for your help!

-- Hsin

**Comment by langjidong** [comment]
Dear Hsin,

Thanks for your attention and using NanoSTR.

There is no limit to stepsize in principle, but we suggestion that you should not set the parameter too large or too small, and we set it to 10 in our paper.

It should be noted that the configure file is important and necessary, and the coordinate position of the STR site should be the version of hg38. Please read our paper for more details.

Unfortunately, NanoSTR does not currently support data in fasta format, so you will need to convert fasta to fastq. I can give you a perl program, maybe can help you solve this problem. Please run the command "less test.fasta|grep -v ">"|perl simulate_quality.pl - test.fastq".

Hope our reply can help you, thank you again for your suggestions and letters.

Best regards,

Jidong Lang
________________________________
发件人: HLHsieh ***@***.***>
发送时间: 2023年8月4日 1:39
收件人: langjidong/NanoSTR ***@***.***>
抄送: Subscribed ***@***.***>
主题: [langjidong/NanoSTR] Question about step size and input file (Issue #2)


Hi there,

Thank you for providing this exciting tool. I am new to this field, so I hope my question is not too naive. I am wondering how to set the "Step Size." Are there any suggestions or thinking tips for using it with my own data? Additionally, I would like to know whether this algorithm accepts a fasta file as an input.

Thank you for your help!

-- Hsin

―

**Comment by HLHsieh** [comment]
Hi Jidong,

I appreciate your prompt response. This Perl program will be helpful; however, I did not find it in any folders.

Additionally, I have one more question. You mentioned that the configuration file is important and necessary. For the coordinate position of the STR, how should I specify it? In other words, does the program accept imperfect repeats, use the input from the result of TRF, or utilize positions that might contain non-repeat regions?

Thank you for your assistance!

-- Hsin

**Comment by HLHsieh** [comment]
Hi Jidong,

I would like to follow up on this issue and kindly request any insights or solutions you might have regarding it. Your assistance is greatly appreciated.

-- Hsin

**Comment by langjidong** [comment]
Dear Hsin,

So sorry for the late reply!


  1.  I have put the Perl program as a attachment file in the last reply e-mail. Could you find it? If not, plz give me your e-mail, I can send it to you again!
  2.  As we said, the configure file of str.bed is necessary, the format just like as follows:
[cid:2400cf3f-f0d7-4853-a551-442f46c7c67d]
But for the TRF or utilize positions that might contain non-repeat regions, we have not test our method on these data, so you may need to do some testing. Of course, we will do some similar data analysis, to expand the scope of application of our method.

Hope that helps, and thanks for your suggestions.😊

Best regards,

Jidong Lang
________________________________
发件人: HLHsieh ***@***.***>
发送时间: 2023年8月23日 18:29
收件人: langjidong/NanoSTR ***@***.***>
抄送: langjidong ***@***.***>; Comment ***@***.***>
主题: Re: [langjidong/NanoSTR] Question about step size and input file (Issue #2)


Hi Jidong,

I would like to follow up on this issue to seek any solutions for this. I would appreciate it if you could give me more hints on it.

-- Hsin

**Comment by HLHsieh** [comment]
Hi Dr. Lang,

I am Hsin-Lun Hsieh, a PhD student at The Ohio State University. We have previously communicated on GitHub regarding the utilization of the remarkable NanoSTR algorithm. I greatly appreciate your assistance thus far.

However, I seem to have missed receiving the Perl program. Could you kindly resend it to me via this email address?  Additionally, I have encountered some confusion regarding the format of str.bed: [cid:2400cf3f-f0d7-4853-a551-442f46c7c67d]. I would greatly appreciate it if you could provide a brief clarification on this.

Thank you for your time and support. I look forward to your response.

Best regards,
Hsin-Lun
________________________________

**Comment by HLHsieh** [comment]
Hi Dr. Lang,

I am following up on this email in case you didn't receive it.

Thanks,
Hsin-Lun
________________________________

**Comment by HLHsieh** [comment]
Hi Jidong,

I seem to have missed receiving the Perl program. Could you kindly resend it to me via this email address: hsieh.332@osu.edu?  Additionally, I have encountered some confusion regarding the format of str.bed: [cid:2400cf3f-f0d7-4853-a551-442f46c7c67d]. I would greatly appreciate it if you could provide a brief clarification on this.

I look forward to your response.

-- Hsin

**Comment by langjidong** [comment]
Dear Hsin,

So sorry for the late reply!

The attachment file is the perl program, which could convert fasta to fastq, maybe can help you solve your problem. Please run the command "gzip -dc simulate_quality.pl.gz > simulate_quality.pl" and "less your.fasta|grep -v ">"|perl simulate_quality.pl - yourfile.fastq".

As we said, the configure file of str.bed is necessary, the format just like as follows (chromosome\tstart_position\tend_positon\tSTR_ID):
[cid:b6428ba6-9daf-4286-8fb5-99344d54d463]
And pay attention to the genome reference version (hg19 or hg38-default).

Hope our reply can help you, thank you again for your suggestions and letters. If you have any questions, let us known!

Best regards,

Jidong Lang
________________________________
发件人: HLHsieh ***@***.***>
发送时间: 2023年9月6日 20:45
收件人: langjidong/NanoSTR ***@***.***>
抄送: langjidong ***@***.***>; Comment ***@***.***>
主题: Re: [langjidong/NanoSTR] Question about step size and input file (Issue #2)


Hi Jidong,

I seem to have missed receiving the Perl program. Could you kindly resend it to me via this email address: ***@***.******@***.***>? Additionally, I have encountered some confusion regarding the format of str.bed: [cid:2400cf3f-f0d7-4853-a551-442f46c7c67d]. I would greatly appreciate it if you could provide a brief clarification on this.

I look forward to your response.

-- Hsin

―

**Comment by HLHsieh** [comment]
Hi Jidong,

Thanks for your response.  I have a few follow-up questions:

1) I tested the demo data you uploaded and executed the script exactly as provided.
```
cat ONT.fastq.tar.bz2.aa ONT.fastq.tar.bz2.ab ONT.fastq.tar.bz2.ac ONT.fastq.tar.bz2.ad ONT.fastq.tar.bz2.ae ONT.fastq.tar.bz2.af|tar jxvf -
chmod -R 755 ../bin
gzip -dc ../database/by_chr/chrY.fa.gz > ../database/by_chr/chrY.fa

perl ../NanoStrTyping.pl -fq ONT.fastq -step_size 10 -configure str.bed -tmp_dir tmpdir -process 4

perl ../script/Typing_predict.pl Typing_Result/DYS392/ 3 10 0
perl ../script/Typing_predict.pl Typing_Result/DYS438/ 5 10 0
perl ../script/Typing_predict.pl Typing_Result/DYS448/ 6 10 42
perl ../script/Typing_predict.pl Typing_Result/DYS635/ 4 10 0

less Typing_Result/DYS392/predict.result
less Typing_Result/DYS438/predict.result
less Typing_Result/DYS448/predict.result
less Typing_Result/DYS635/predict.result
``` 

However, I encountered some errors:
```
ONT.fastq
Process: 0%----Data Pre-process and Quality Control Start. Time: Sat Sep  9 21:27:51 EDT 2023
Process: 20%----Data Pre-process and Quality Control End and Generate Seed Sequence List Start. Time: Sat Sep  9 21:31:54 EDT 2023
Process: 40%----Generate Seed Sequence List End and Pick Target Reads Based On Seed List Start. Time: Sat Sep  9 21:32:28 EDT 2023
Process: 60%----Pick Target Reads Based On Seed List End and Blast Alignment Start. Time: Sat Sep  9 21:34:24 EDT 2023
Process: 80%----Blast Alignment End and Result Output Start. Time: Sat Sep  9 22:56:18 EDT 2023
Blast/DYS392/Tmp1.filter.info: No such file or directory
Blast/DYS392/Tmp2.filter.info: No such file or directory
Blast/DYS392/Tmp3.filter.info: No such file or directory
Blast/DYS392/Tmp4.filter.info: No such file or directory
Blast/DYS392/Tmp5.filter.info: No such file or directory
Blast/DYS392/Tmp6.filter.info: No such file or directory
Blast/DYS392/Tmp7.filter.info: No such file or directory
Blast/DYS392/Tmp8.filter.info: No such file or directory
Blast/DYS392/Tmp9.filter.info: No such file or directory
Blast/DYS392/Tmp10.filter.info: No such file or directory
Blast/DYS438/Tmp1.filter.info: No such file or directory
Blast/DYS438/Tmp2.filter.info: No such file or directory
Blast/DYS438/Tmp3.filter.info: No such file or directory
Blast/DYS438/Tmp4.filter.info: No such file or directory
Blast/DYS438/Tmp5.filter.info: No such file or directory
Blast/DYS438/Tmp6.filter.info: No such file or directory
Blast/DYS438/Tmp7.filter.info: No such file or directory
Blast/DYS438/Tmp8.filter.info: No such file or directory
Blast/DYS438/Tmp9.filter.info: No such file or directory
Blast/DYS438/Tmp10.filter.info: No such file or directory
Blast/DYS448/Tmp1.filter.info: No such file or directory
Blast/DYS448/Tmp2.filter.info: No such file or directory
Blast/DYS448/Tmp3.filter.info: No such file or directory
Blast/DYS448/Tmp4.filter.info: No such file or directory
Blast/DYS448/Tmp5.filter.info: No such file or directory
Blast/DYS448/Tmp6.filter.info: No such file or directory
Blast/DYS448/Tmp7.filter.info: No such file or directory
Blast/DYS448/Tmp8.filter.info: No such file or directory
Blast/DYS448/Tmp9.filter.info: No such file or directory
Blast/DYS448/Tmp10.filter.info: No such file or directory
Blast/DYS635/Tmp1.filter.info: No such file or directory
Blast/DYS635/Tmp2.filter.info: No such file or directory
Blast/DYS635/Tmp3.filter.info: No such file or directory
Blast/DYS635/Tmp4.filter.info: No such file or directory
Blast/DYS635/Tmp5.filter.info: No such file or directory
Blast/DYS635/Tmp6.filter.info: No such file or directory
Blast/DYS635/Tmp7.filter.info: No such file or directory
Blast/DYS635/Tmp8.filter.info: No such file or directory
Blast/DYS635/Tmp9.filter.info: No such file or directory
Blast/DYS635/Tmp10.filter.info: No such file or directory
Process: 100%----Result Output End and All tasks completed. Time: Sat Sep  9 22:56:31 EDT 2023
```
Could you please provide guidance on how to address this issue?"

2) I am wondering how crucial the quality of the reads is for the analysis and whether it's ok to apply simulated quality scores to this algorithm.

Thank you for your assistance.

Thanks,
Hsin
