### ISSUE TITLE
Error regarding test data

### ISSUE THREAD

**Issue by HLHsieh** [langjidong/NanoSTR#3]
Hi Jidong,

I have a few follow-up questions:

1) I tested the demo data you uploaded and executed the script exactly as provided.
```
cat ONT.fastq.tar.bz2.aa ONT.fastq.tar.bz2.ab ONT.fastq.tar.bz2.ac ONT.fastq.tar.bz2.ad ONT.fastq.tar.bz2.ae ONT.fastq.tar.bz2.af|tar jxvf -
chmod -R 755 ../bin
gzip -dc ../database/by_chr/chrY.fa.gz > ../database/by_chr/chrY.fa

perl ../NanoStrTyping.pl -fq ONT.fastq -step_size 10 -configure str.bed -tmp_dir tmpdir -process 4

perl ../script/Typing_predict.pl Typing_Result/DYS392/ 3 10 0
perl ../script/Typing_predict.pl Typing_Result/DYS438/ 5 10 0
perl ../script/Typing_predict.pl Typing_Result/DYS448/ 6 10 42
perl ../script/Typing_predict.pl Typing_Result/DYS635/ 4 10 0

less Typing_Result/DYS392/predict.result
less Typing_Result/DYS438/predict.result
less Typing_Result/DYS448/predict.result
less Typing_Result/DYS635/predict.result
``` 

However, I encountered some errors:
```
ONT.fastq
Process: 0%----Data Pre-process and Quality Control Start. Time: Sat Sep  9 21:27:51 EDT 2023
Process: 20%----Data Pre-process and Quality Control End and Generate Seed Sequence List Start. Time: Sat Sep  9 21:31:54 EDT 2023
Process: 40%----Generate Seed Sequence List End and Pick Target Reads Based On Seed List Start. Time: Sat Sep  9 21:32:28 EDT 2023
Process: 60%----Pick Target Reads Based On Seed List End and Blast Alignment Start. Time: Sat Sep  9 21:34:24 EDT 2023
Process: 80%----Blast Alignment End and Result Output Start. Time: Sat Sep  9 22:56:18 EDT 2023
Blast/DYS392/Tmp1.filter.info: No such file or directory
Blast/DYS392/Tmp2.filter.info: No such file or directory
Blast/DYS392/Tmp3.filter.info: No such file or directory
Blast/DYS392/Tmp4.filter.info: No such file or directory
Blast/DYS392/Tmp5.filter.info: No such file or directory
Blast/DYS392/Tmp6.filter.info: No such file or directory
Blast/DYS392/Tmp7.filter.info: No such file or directory
Blast/DYS392/Tmp8.filter.info: No such file or directory
Blast/DYS392/Tmp9.filter.info: No such file or directory
Blast/DYS392/Tmp10.filter.info: No such file or directory
Blast/DYS438/Tmp1.filter.info: No such file or directory
Blast/DYS438/Tmp2.filter.info: No such file or directory
Blast/DYS438/Tmp3.filter.info: No such file or directory
Blast/DYS438/Tmp4.filter.info: No such file or directory
Blast/DYS438/Tmp5.filter.info: No such file or directory
Blast/DYS438/Tmp6.filter.info: No such file or directory
Blast/DYS438/Tmp7.filter.info: No such file or directory
Blast/DYS438/Tmp8.filter.info: No such file or directory
Blast/DYS438/Tmp9.filter.info: No such file or directory
Blast/DYS438/Tmp10.filter.info: No such file or directory
Blast/DYS448/Tmp1.filter.info: No such file or directory
Blast/DYS448/Tmp2.filter.info: No such file or directory
Blast/DYS448/Tmp3.filter.info: No such file or directory
Blast/DYS448/Tmp4.filter.info: No such file or directory
Blast/DYS448/Tmp5.filter.info: No such file or directory
Blast/DYS448/Tmp6.filter.info: No such file or directory
Blast/DYS448/Tmp7.filter.info: No such file or directory
Blast/DYS448/Tmp8.filter.info: No such file or directory
Blast/DYS448/Tmp9.filter.info: No such file or directory
Blast/DYS448/Tmp10.filter.info: No such file or directory
Blast/DYS635/Tmp1.filter.info: No such file or directory
Blast/DYS635/Tmp2.filter.info: No such file or directory
Blast/DYS635/Tmp3.filter.info: No such file or directory
Blast/DYS635/Tmp4.filter.info: No such file or directory
Blast/DYS635/Tmp5.filter.info: No such file or directory
Blast/DYS635/Tmp6.filter.info: No such file or directory
Blast/DYS635/Tmp7.filter.info: No such file or directory
Blast/DYS635/Tmp8.filter.info: No such file or directory
Blast/DYS635/Tmp9.filter.info: No such file or directory
Blast/DYS635/Tmp10.filter.info: No such file or directory
Process: 100%----Result Output End and All tasks completed. Time: Sat Sep  9 22:56:31 EDT 2023
```
Could you please provide guidance on how to address this issue?"

2) I am wondering how crucial the quality of the reads is for the analysis and whether it's ok to apply simulated quality scores to this algorithm.

Thank you for your assistance.

Thanks,
Hsin

**Comment by langjidong** [comment]
Dear Hsin,

Sorry for the late reply!

1. I have checked and run the the demo data, but I didn't find any error. So plz check your command lines and the error-log files, I think maybe you lost some necessary software or tools, plz check the perl script. And if NanoSTR did not show the error information, you should try to comment out/block/delete some command lines, such as the Process lines in the perl script.

2. The quality of sequencing reads reflects the accuracy of the sequencing data, so it is very important for data analysis. NanoSTR needs to be used under the condition of a certain sequencing accuracy, and theoretically, the higher the sequencing quality, that is, the more accurate the sequencing, the more accurate the analysis results of NanoSTR. However, if you only have data in fasta format, you may only be able to adapt the input format of this method using the simulated quality score method, but the q-value was not used in the actual data analysis.

Hope that can help you!

Best regards,

Jidong Lang

________________________________
发件人: HLHsieh ***@***.***>
发送时间: 2023年9月18日 20:35
收件人: langjidong/NanoSTR ***@***.***>
抄送: Subscribed ***@***.***>
主题: [langjidong/NanoSTR] Error regarding test data (Issue #3)


Hi Jidong,

I have a few follow-up questions:

  1.  I tested the demo data you uploaded and executed the script exactly as provided.

cat ONT.fastq.tar.bz2.aa ONT.fastq.tar.bz2.ab ONT.fastq.tar.bz2.ac ONT.fastq.tar.bz2.ad ONT.fastq.tar.bz2.ae ONT.fastq.tar.bz2.af|tar jxvf -
chmod -R 755 ../bin
gzip -dc ../database/by_chr/chrY.fa.gz > ../database/by_chr/chrY.fa

perl ../NanoStrTyping.pl -fq ONT.fastq -step_size 10 -configure str.bed -tmp_dir tmpdir -process 4

perl ../script/Typing_predict.pl Typing_Result/DYS392/ 3 10 0
perl ../script/Typing_predict.pl Typing_Result/DYS438/ 5 10 0
perl ../script/Typing_predict.pl Typing_Result/DYS448/ 6 10 42
perl ../script/Typing_predict.pl Typing_Result/DYS635/ 4 10 0

less Typing_Result/DYS392/predict.result
less Typing_Result/DYS438/predict.result
less Typing_Result/DYS448/predict.result
less Typing_Result/DYS635/predict.result


However, I encountered some errors:

ONT.fastq
Process: 0%----Data Pre-process and Quality Control Start. Time: Sat Sep  9 21:27:51 EDT 2023
Process: 20%----Data Pre-process and Quality Control End and Generate Seed Sequence List Start. Time: Sat Sep  9 21:31:54 EDT 2023
Process: 40%----Generate Seed Sequence List End and Pick Target Reads Based On Seed List Start. Time: Sat Sep  9 21:32:28 EDT 2023
Process: 60%----Pick Target Reads Based On Seed List End and Blast Alignment Start. Time: Sat Sep  9 21:34:24 EDT 2023
Process: 80%----Blast Alignment End and Result Output Start. Time: Sat Sep  9 22:56:18 EDT 2023
Blast/DYS392/Tmp1.filter.info: No such file or directory
Blast/DYS392/Tmp2.filter.info: No such file or directory
Blast/DYS392/Tmp3.filter.info: No such file or directory
Blast/DYS392/Tmp4.filter.info: No such file or directory
Blast/DYS392/Tmp5.filter.info: No such file or directory
Blast/DYS392/Tmp6.filter.info: No such file or directory
Blast/DYS392/Tmp7.filter.info: No such file or directory
Blast/DYS392/Tmp8.filter.info: No such file or directory
Blast/DYS392/Tmp9.filter.info: No such file or directory
Blast/DYS392/Tmp10.filter.info: No such file or directory
Blast/DYS438/Tmp1.filter.info: No such file or directory
Blast/DYS438/Tmp2.filter.info: No such file or directory
Blast/DYS438/Tmp3.filter.info: No such file or directory
Blast/DYS438/Tmp4.filter.info: No such file or directory
Blast/DYS438/Tmp5.filter.info: No such file or directory
Blast/DYS438/Tmp6.filter.info: No such file or directory
Blast/DYS438/Tmp7.filter.info: No such file or directory
Blast/DYS438/Tmp8.filter.info: No such file or directory
Blast/DYS438/Tmp9.filter.info: No such file or directory
Blast/DYS438/Tmp10.filter.info: No such file or directory
Blast/DYS448/Tmp1.filter.info: No such file or directory
Blast/DYS448/Tmp2.filter.info: No such file or directory
Blast/DYS448/Tmp3.filter.info: No such file or directory
Blast/DYS448/Tmp4.filter.info: No such file or directory
Blast/DYS448/Tmp5.filter.info: No such file or directory
Blast/DYS448/Tmp6.filter.info: No such file or directory
Blast/DYS448/Tmp7.filter.info: No such file or directory
Blast/DYS448/Tmp8.filter.info: No such file or directory
Blast/DYS448/Tmp9.filter.info: No such file or directory
Blast/DYS448/Tmp10.filter.info: No such file or directory
Blast/DYS635/Tmp1.filter.info: No such file or directory
Blast/DYS635/Tmp2.filter.info: No such file or directory
Blast/DYS635/Tmp3.filter.info: No such file or directory
Blast/DYS635/Tmp4.filter.info: No such file or directory
Blast/DYS635/Tmp5.filter.info: No such file or directory
Blast/DYS635/Tmp6.filter.info: No such file or directory
Blast/DYS635/Tmp7.filter.info: No such file or directory
Blast/DYS635/Tmp8.filter.info: No such file or directory
Blast/DYS635/Tmp9.filter.info: No such file or directory
Blast/DYS635/Tmp10.filter.info: No such file or directory
Process: 100%----Result Output End and All tasks completed. Time: Sat Sep  9 22:56:31 EDT 2023


Could you please provide guidance on how to address this issue?"

  1.  I am wondering how crucial the quality of the reads is for the analysis and whether it's ok to apply simulated quality scores to this algorithm.

Thank you for your assistance.

Thanks,
Hsin

―

**Comment by rayljc** [comment]
Hi Jidong (@langjidong ),

I am also facing the same issue (the error looks pretty the same). I have verified that I have installed ```Porechop 0.2.4```, ```NanoPlot 1.41.6```, and granted the /bin folder including blastall and formatdb full read/write/execute permissions. Still, I am seeing the Blast ```No such file or directory``` errors.

I am suspecting it's due to the Porechop and NanoPlot version I am using. Can you please share the Porechop and NanoPlot version you are using? Thank you!

Best Regards,
Ray
