### ISSUE TITLE
ONT Update to Raw Readout in Pod5 Format

### ISSUE THREAD

**Issue by natashaberthold** [langjidong/NanoSTR#4]
I have a quick question relating to the latest ONT basecaller update, Dorado, and the change to outputting raw data in Pod5. I have noticed this tool still requires a fastq input, however, with Dorado basecalling it takes the poid5 and merges the step for basecalling and alignment, outputting in bam format. Does this mean that to apply NanoSTR I would have to convert the pod5 files back to fast5 format and bascall them instead to get fastq to input?
Cheers!

**Comment by langjidong** [comment]
Dear Natasha,

I am so sorry that NanoSTR has to use fastq format as the input file when you use it. If the Dorado's aligned reference genome was the same as what you wanted to use, I think you should use the bam2fastq or samtools fastq command to convert bam to fastq file directly. But if not, I'm afraid that you have to convert the pod5 files back to fast5 format and redo the basecalling.

Hope that can help you!

Best regards,

Jidong Lang
________________________________
发件人: Natasha Berthold ***@***.***>
发送时间: 2023年9月22日 3:03
收件人: langjidong/NanoSTR ***@***.***>
抄送: Subscribed ***@***.***>
主题: [langjidong/NanoSTR] ONT Update to Raw Readout in Pod5 Format (Issue #4)


I have a quick question relating to the latest ONT basecaller update, Dorado, and the change to outputting raw data in Pod5. I have noticed this tool still requires a fastq input, however, with Dorado basecalling it takes the poid5 and merges the step for basecalling and alignment, outputting in bam format. Does this mean that to apply NanoSTR I would have to convert the pod5 files back to fast5 format and bascall them instead to get fastq to input?
Cheers!

―
